version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    container_name: spring-redis
    image: spring:latest
    build: .
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "8080:8080"

